<style>
    .testpdf{
        font-weight: bold;
    }
</style>

<div class='testpdf'>
    trololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
    lolololololololololololololololololololololololololololololololololololololo
</div>
