-- house 1
INSERT INTO `roommates`.`houses` (	`address`,
									`postal_code`,
									`area`,
									`bedroom_num`,
									`bathroom_num`,
									`price`,
									`construction_year`,
									`solar_heater`,
									`furnitured`,
									`aircondition`,
									`garden`,
									`parking`,
									`shared_pay`,
									`security_doors`,
									`disability_facilities`,
									`storeroom`,
									`availability_date`,
									`rent_period`,
									`description`,
									`created`,
									`modified`,
									`floor_id`,
									`house_type_id`,
									`heating_type_id`,
									`currently_hosting`,
									`total_places`,
									`profile_id`,
									`municipality_id`	)

						VALUES	(	'address 1',
									'11111',
									45,
									3,
									1,
									340,
									NULL,
									1,
									1,
									1,
									0,
									0,
									1,
									0,
									0,
									0,
									'2011-11-05',
									NULL,
									'This is the first house!',
									NOW(),
									NOW(),
									3,
									2,
									2,
									1,
									3,
									1,
									11	);

-- house 2
INSERT INTO `roommates`.`houses` (	`address`,
									`postal_code`,
									`area`,
									`bedroom_num`,
									`bathroom_num`,
									`price`,
									`construction_year`,
									`solar_heater`,
									`furnitured`,
									`aircondition`,
									`garden`,
									`parking`,
									`shared_pay`,
									`security_doors`,
									`disability_facilities`,
									`storeroom`,
									`availability_date`,
									`rent_period`,
									`description`,
									`created`,
									`modified`,
									`floor_id`,
									`house_type_id`,
									`heating_type_id`,
									`currently_hosting`,
									`total_places`,
									`profile_id`,
									`municipality_id`	)

						VALUES	(	'address 2',
									'11111',
									55,
									3,
									1,
									380,
									NULL,
									1,
									1,
									1,
									0,
									0,
									1,
									0,
									0,
									0,
									'2011-11-05',
									NULL,
									'This is the second house!',
									NOW(),
									NOW(),
									1,
									2,
									2,
									1,
									3,
									2,
									22	);

-- house 3
INSERT INTO `roommates`.`houses` (	`address`,
									`postal_code`,
									`area`,
									`bedroom_num`,
									`bathroom_num`,
									`price`,
									`construction_year`,
									`solar_heater`,
									`furnitured`,
									`aircondition`,
									`garden`,
									`parking`,
									`shared_pay`,
									`security_doors`,
									`disability_facilities`,
									`storeroom`,
									`availability_date`,
									`rent_period`,
									`description`,
									`created`,
									`modified`,
									`floor_id`,
									`house_type_id`,
									`heating_type_id`,
									`currently_hosting`,
									`total_places`,
									`profile_id`,
									`municipality_id`	)

						VALUES	(	'address 2',
									'11111',
									35,
									2,
									1,
									280,
									NULL,
									1,
									1,
									1,
									0,
									0,
									1,
									0,
									0,
									0,
									'2011-11-05',
									NULL,
									'This is the second house!',
									NOW(),
									NOW(),
									6,
									1,
									3,
									1,
									3,
									3,
									33	);
