INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'υπόγειο');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'ημιυπόγειο');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'υπερυψωμένο');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'ισόγειο');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'ημιόροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'1ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'2ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'3ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'4ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'5ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'6ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'7ος όροφος');
INSERT INTO `roommates`.`floors` (`id`,`type`) VALUES (NULL,'8+ όροφος');
